services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/committee_portal
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mongo-data:


